routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('/Mahasiswa', \App\Http\Controllers\MahasiswaController::Class);

app/Http/Controllers/MahasiswaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;

class MahasiswaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = DB::select(DB::raw("select * from Mahasiswa"));
        return view('Mahasiswa.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Mahasiswa.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'nama_mahasiswa_2257301031' => 'required',
            'tempat_lahir' => 'required',
            'tanggal_lahir' => 'required',
            'no_hp' => 'required',
            'email' => 'required'
        ]);

        DB::insert(
            "INSERT INTO `Mahasiswa` (`id`, `nama_mahasiswa_2257301031`, `tempat_lahir`, `tanggal_lahir`, `no_hp`, `email`) VALUES (uuid(), ?, ?, ?, ?, ?)",
            [$request->nama_mahasiswa_2257301031, $request->tempat_lahir, $request->tanggal_lahir, $request->no_hp, $request->email]
        );
        return redirect()->route('Mahasiswa.index')->with(['success' => 'Data Berhasil Disimpan!']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = DB::table('Mahasiswa')->where('id', $id)->first();
        return view('Mahasiswa.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'nama_mahasiswa_2257301031' => 'required',
            'tempat_lahir' => 'required',
            'tanggal_lahir' => 'required',
            'no_hp' => 'required',
            'email' => 'required'
        ]);

        DB::update("UPDATE `Mahasiswa` SET `nama_mahasiswa_2257301031`=?,`tempat_lahir`=?,`tanggal_lahir`=?, `no_hp`=?, `email`=? WHERE id=?",
            [$request->nama_mahasiswa_2257301031, $request->tempat_lahir, $request->tanggal_lahir, $request->no_hp, $request->email, $id]);
        return redirect()->route('Mahasiswa.index')->with(['success' => 'Data Berhasil Diupdate!']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::table('Mahasiswa')->where('id', $id)->delete();
        //redirect to index
        return redirect()->route('Mahasiswa.index')->with(['success' => 'Data Berhasil Dihapus!']);
    }
}

resources/views/Mahasiswa/create.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Tambah Data Mahasiswa - Penerimaan Mahasiswa Baru</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>

<body style="background: lightgray">
    <div class="container mt-5 mb-5">
        <div class="row">
            <div class="col-md-12">
                <div class="card border-0 shadow rounded">
                    <div class="card-body">
                        <form action="{{ route('Mahasiswa.store') }}" method="post" enctype="multipart/form-data">
                            @csrf
                            <div class="form-group">
                                <label class="font-weight-bold">NAMA MAHASISWA</label>
                                <input type="text" class="form-control @error('nama_mahasiswa_2257301031') is-invalid @enderror" name="nama_mahasiswa_2257301031" placeholder="Nama Mahasiswa">
                                <!-- error message untuk nama mahasiswa -->
                                @error('nama_mahasiswa_2257301031')
                                <div class="alert alert-dangermt-2">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label class="font-weight-bold">TEMPAT LAHIR</label>
                                <input type="text" class="form-control @error('tempat_lahir') is-invalid @enderror" name="tempat_lahir">
                                <!-- error message untuk due_date-->
                                @error('tempat_lahir')
                                <div class=" alert alert-danger mt-2">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label class="font-weight-bold">TANGGAL LAHIR</label>
                                <input type="date" class="form-control @error('tanggal_lahir') is-invalid @enderror" name="tanggal_lahir">
                                <!-- error message untuk cost -->
                                @error('tanggal_lahir')
                                <div class="alert alert-dangermt-2">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label class="font-weight-bold">NO HP</label>
                                <input type="text" class="form-control @error('no_hp') is-invalid @enderror" name="no_hp">
                                <!-- error message untuk cost -->
                                @error('no_hp')
                                <div class="alert alert-dangermt-2">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label class="font-weight-bold">Email</label>
                                <input type="text" class="form-control @error('email') is-invalid @enderror" name="email">
                                <!-- error message untuk cost -->
                                @error('email')
                                <div class="alert alert-dangermt-2">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>


                            <button type="submit" class="btn btn-mdbtn-primary">SIMPAN</button>
                            <button type="reset" class="btn btn-mdbtn-warning">RESET</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdn.ckeditor.com/4.13.1/standard/ckeditor.js"></script>
</body>

</html>

resources/views/Mahasiswa/edit.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Tambah Data Mahasiswa - Penerimaan Mahasiswa Baru</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>

<body style="background: lightgray">
    <div class="container mt-5 mb-5">
        <div class="row">
            <div class="col-md-12">
                <div class="card border-0 shadow rounded">
                    <div class="card-body">
                        <form action="{{ route('Mahasiswa.update',$data->id) }}" method="post" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label class="font-weight-bold">NAMA MAHASISWA</label>
                                <input type="text" class="form-control @error('nama_mahasiswa_2257301031') is-invalid @enderror" name="nama_mahasiswa_2257301031" value="{{ $data->nama_mahasiswa_2257301031}}">
                                <!-- error message untuk title -->
                                @error('nama_mahasiswa_2257301031')
                                <div class="alert alert-dangermt-2">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label class="font-weight-bold">TEMPAT LAHIR</label>
                                <input type="text" class="form-control @error('tempat_lahir') is-invalid @enderror" name="tempat_lahir" value="{{ $data->tempat_lahir}}">
                                <!-- error message untuk cost -->
                                @error('tempat_lahir')
                                <div class="alert alert-dangermt-2">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label class="font-weight-bold">TANGGAL LAHIR</label>
                                <input type="date" class="form-control @error('due_date') is-invalid @enderror" name="tanggal_lahir" value="{{ $data->tanggal_lahir}}">
                                <!-- error message untuk due_date-->
                                @error('tanggal_lahir')
                                <div class="alert alert-dangermt-2">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label class="font-weight-bold">NO HP</label>
                                <input type="text" class="form-control @error('no_hp') is-invalid @enderror" name="no_hp" value="{{ $data->no_hp}}">
                                <!-- error message untuk due_date-->
                                @error('no_hp')
                                <div class="alert alert-dangermt-2">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label class="font-weight-bold">email</label>
                                <input type="text" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ $data->email}}">
                                <!-- error message untuk due_date-->
                                @error('email')
                                <div class="alert alert-dangermt-2">
                                    {{ $message }}
                                </div>
                                @enderror
                            </div>
                            <button type="submit" class="btn btn-mdbtn-primary">SIMPAN</button>
                            <button type="reset" class="btn btn-mdbtn-warning">RESET</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdn.ckeditor.com/4.13.1/standard/ckeditor.js"></script>
</body>
</html>

resources/views/Mahasiswa/index.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Data Mahasiswa - Penerimaan Mahasiswa Baru</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.ss">
</head>

<body style="background: lightgray">
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-12">
                <div class="card border-0 shadow rounded">
                    <div class="card-body">
                        <a href="{{ route('Mahasiswa.create') }}" class="btn btn-md btn-success mb-3">TAMBAH MAHASISWA</a>
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th scope="col">NAMA MAHASISWA</th>
                                    <th scope="col">TEMPAT LAHIR</th>
                                    <th scope="col">TANGGAL LAHIR</th>
                                    <th scope="col">NO HP</th>
                                    <th scope="col">EMAIL</th>
                                    <th scope="col">AKSI</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($data as $mahasiswa)
                                <tr>
                                    <td>{{ $mahasiswa->nama_mahasiswa_2257301031}}</td>
                                    <td>{{ $mahasiswa->tempat_lahir}}</td>
                                    <td>{{$mahasiswa->tanggal_lahir}}</td>
                                    <td>{{ $mahasiswa->no_hp}}</td>
                                    <td>{{$mahasiswa->email}}</td>

                                    <td class="text-center">
                                        <form onsubmit="return confirm('Apakah Anda Yakin ?');" action="{{route('mahasiswa.destroy', $mahasiswa->id) }}" method="post">
                                            <a href="{{route('mahasiswa.edit', $mahasiswa->id) }}" class="btn btn-sm btn-primary">EDIT</a>
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-sm btn-danger">HAPUS</button>
                                        </form>
                                    </td>
                                </tr>
                                @empty
                                <div class="alert alert-danger">
                                    Data mahasiswa belum Tersedia.
                                </div>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script>
        //message with toastr
        @if(session() -> has('success'))
        toastr.success('{{ session ('success')}}', 'BERHASIL!');
        @elseif(session() -> has('error'))
        toastr.error('{{ session('error')}}', 'GAGAL!');
        @endif
    </script>
</body>
</html>